# Generated by Django 2.0.4 on 2018-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0006_auto_20180518_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
