# Generated by Django 2.0.4 on 2018-05-19 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0008_carbooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooked',
            name='datebooked',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
