# Generated by Django 2.0.4 on 2018-05-19 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0009_carbooked_datebooked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooked',
            old_name='datebooked',
            new_name='frombooked',
        ),
        migrations.AddField(
            model_name='carbooked',
            name='note',
            field=models.TextField(default='ciao'),
        ),
        migrations.AddField(
            model_name='carbooked',
            name='tobooked',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
