# Generated by Django 2.0.4 on 2018-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0010_auto_20180519_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooked',
            name='note',
            field=models.TextField(default='Aggiungi note..'),
        ),
        migrations.RemoveField(
            model_name='carbooked',
            name='username',
        ),
        migrations.AddField(
            model_name='carbooked',
            name='username',
            field=models.ManyToManyField(to='CarApp.User'),
        ),
    ]
