# Generated by Django 2.0.4 on 2018-05-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0011_auto_20180519_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooked',
            name='username',
        ),
        migrations.AddField(
            model_name='carbooked',
            name='username',
            field=models.ForeignKey(default='bo', on_delete=django.db.models.deletion.CASCADE, to='CarApp.User'),
        ),
    ]
