# Generated by Django 2.0.4 on 2018-05-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0012_auto_20180519_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooked',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CarApp.User'),
        ),
    ]
