# Generated by Django 2.0.4 on 2018-05-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0014_auto_20180519_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooked',
            name='model',
        ),
        migrations.RemoveField(
            model_name='carbooked',
            name='username',
        ),
        migrations.DeleteModel(
            name='CarBooked',
        ),
    ]
