# Generated by Django 2.0.4 on 2018-05-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0016_carbooked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarBooked',
            new_name='CarBook',
        ),
    ]
